### ISSUE TITLE
Node stopped

### ISSUE THREAD

**Issue by Skill127** [Concordium/Testnet4-Challenges#123]
https://discord.com/channels/667378330923696158/687313907500449849/806810700756287498

Hello, the node has been running for 14 days. On February 4, difficulties began to be observed throughout the network. My node went down. As per your request, I am attaching my logs.
https://drive.google.com/file/d/1IPGJ3BXSZ3U7gB_IxLKe_sYIcQQq9N3J/view?usp=sharing

What to do with OT4-T1 OT4-T2 OT4-T3 tasks, according to the conditions they should run every day without interruption, node failures do not allow to execute them according to all the rules.

**Comment by concordium-cl** [comment]
At the moment and starting last night, there are a lot of transaction in most blocks, much more than what we have seen in the days before. We have also seen that many nodes with specs below what we recommend stopped, possibly by running out of memory.

The transaction challenges don't have to be completed on consecutive days, meaning we request 7 days with the specified load of successful transaction not 7 consecutive days. Furthermore, the submission deadline is first 17-02.

**Comment by concordium-cl** [comment]
We have an update available. Please follow our instructions on the [status page](https://github.com/Concordium/Testnet4-Challenges/blob/master/status.md) and the [Medium post](https://medium.com/concordium/ot4-high-load-status-report-update-e03a54bd82fc).
