### ISSUE TITLE
Counting transactions

### ISSUE THREAD

**Issue by lesnikutsa** [Concordium/Testnet4-Challenges#132]
Good afternoon - due to the current situation and the problem in sending transactions, will there be changes in the descriptions of tasks T1, T2, T3, T4?
It took me 6 days to send everything like clockwork, but now there are only delays. In the medium, you said that everything is fine on your nodes with 16 GB of RAM, but what should we do? We selected capacities according to your instructions.

**Comment by concordium-cl** [comment]
We have an update available. Please follow our instructions on the [status page](https://github.com/Concordium/Testnet4-Challenges/blob/master/status.md) and the [Medium post](https://medium.com/concordium/ot4-high-load-status-report-update-e03a54bd82fc).
