### ISSUE TITLE
Database invariant violation. See logs for details

### ISSUE THREAD

**Issue by iekmuby** [Concordium/Testnet4-Challenges#139]
Because of high load and fast log increasing I moved my server to the new configuration. I stopped my node and make a snapshot, after create new server with this snapshot. But can't start the node with following error:

> 2021-02-05T12:49:01.540068724Z: ERROR: TreeState: Database invariant violation: Could not read last finalized block
> 2021-02-05T12:49:01.540119305Z: ERROR: External: Database invariant violation: Could not read last finalized block
> Error: ErrorMessage { msg: "Database invariant violation. See logs for details." }

According to [this](https://github.com/Concordium/Testnet3-Challenges/issues/427) Testnet3 issue, I need to flush my DB on node start (`Do you want to flush the local node database before starting? (y/N):`) or I can fix it another way?

**Comment by concordium-cl** [comment]
We have an update available. Please follow our instructions on the [status page](https://github.com/Concordium/Testnet4-Challenges/blob/master/status.md) and the [Medium post](https://medium.com/concordium/ot4-high-load-status-report-update-e03a54bd82fc).
