### ISSUE TITLE
Android wallet wrong balance

### ISSUE THREAD

**Issue by Las-Vegas** [Concordium/Testnet4-Challenges#164]
I have small amount of GTU "At disposal" (between 0-100).
Then I unshielded 800 GTU. Transaction was not finalized but it showed "At disposal": -267 [screen1](https://ibb.co/1vLRJyr)
After finalization "At disposal": 1332 [screen2](https://ibb.co/m0LR2Bt)

account address 3HyAFnogGx12WNdSUMWqbA8wvRJRULbDeSykr8kZ8uBB1orbND
Device: Redmi note 8 pro
Android version: 10 QP1A.190711.020

**Comment by eb-concordium** [comment]
Hi Las-Vegas

This is a bug in the Android app. Thanks a lot for letting us know!

Kind regards,
Emil, Concordium Support
