### ISSUE TITLE
Transactions are no longer displayed in Android mobile wallet. 

### ISSUE THREAD

**Issue by karpiyksi** [Concordium/Testnet4-Challenges#290]
The Android mobile wallet no longer displays transactions on one of the wallets.
There are transactions in Shilded Balance, but not on the main balance.
The loading wheel turns and does not load. Today 2 transactions for baked goods and blocks were loaded. 
Account:
karpiy
32ZrVUrYZmWN3yKtcrxRseXpw14RF6ktAFbntHuKT5vVHXucnM
Nokia 7.2
Android 10
![photo_2021-02-11_23-34-53](https://user-images.githubusercontent.com/54373756/107695625-ed42d480-6cc1-11eb-8bb3-1fa199fbf8aa.jpg)
![photo_2021-02-11_23-34-50](https://user-images.githubusercontent.com/54373756/107695628-ee740180-6cc1-11eb-8894-d6b53c6f945a.jpg)

**Comment by pablozsc** [comment]
I don't know if this has anything to do with this problem, but I would like to ask you to also watch this video, which I just filmed. It clearly shows that the loading of transactions in the application is a little strange - if you scroll down the application, the loading wheel turns endlessly, until I slightly raise the screen.

https://www.youtube.com/watch?v=KcdY9Ggflwk

**Comment by BorisVelikodushniy** [comment]
There was the same problem a few hours ago. The protected wallet information update status spins and nothing happens. Restarting the wallet didn't help. The wallet now works fine after 10 hours.

Samsung galaxy A8 2018
Android 9.0

Harmantest
38Bh4Ez41EDcXPC43XPXUkTNaLTxfd1f1U277Gnr7DzrWiR8Xk

**Comment by jens-concordium** [comment]
Hello all, 

After having discussed this issue with the tech team, we have concluded that it is caused by a known backend issue. This issue usually happens for accounts with a lot of transactions, especially shielded transactions. Unfortunately there is no current work-around for this. 

Thanks for letting us know about this!
