### ISSUE TITLE
Transaction Error! Credential rejected by node

### ISSUE THREAD

**Issue by xmeninx** [Concordium/Testnet4-Challenges#298]
Hello,
I am sending from my main account for T1, T2, T3, T4 tasks. The balance of the main account has decreased. For this reason, I opened a new account on my phone. 2000 gtu loaded. When I wanted to send some of this to my main account, I got an error message.

The message is: "Transaction Error! Credential rejected by node"

Main Address-Recipient Address: "3VyfMQQA4fhmCXuMKnFzKwystN68uS33W3ENWG6JvrhCjndfUE"
New Address-Send Address : "3qW4gPA2mna5EWwRKSopcFWmax42TJUydkPktUVxxZ44NEGXuP"

**Comment by jens-concordium** [comment]
Hello,

Thanks for reaching out. Just to understand the error completely, I have a few questions:

You get this error message while trying to make a transfer from the new account, right?

And, are you trying to make the transaction from the Concordium ID app (if so, which phone and OS do you have?), or do you experience this problem when using the concordium-client?

**Comment by jens-concordium** [comment]
One of our engineers has been digging around, and a potential cause for this problem could be that the time on your phone was not correct, when you tried to make the transfer. Is it possible that the clock is not set correctly on your phone? Maybe you can try updating the time if that's the case, and then let us know if it fixed the problem.

**Comment by xmeninx** [comment]
Yes, my phone time zone has changed. I reinstated it and the problem was solved. 
I am sending gtu from my new account on phone now.
Thanks.

**Comment by jens-concordium** [comment]
Good to hear that it works now.

Thank you, too.
