### ISSUE TITLE
External: Database invariant violation: Could not read last finalized block

### ISSUE THREAD

**Issue by ismailsrbst** [Concordium/Testnet4-Challenges#359]
I'm getting an error message like this. and I guess that's why I can't see my own node in the dashboard. What should I do for this error?

**Comment by abizjak** [comment]
This indicates that your node shut down or was killed and then attempted to restart, but the database was corrupted.

The only solution at the moment is to stop the node, delete the database and restart the node.

If you are on linux or mac then the database is located in `.local/share/concordium/database-v3`. You simply have to delete that directory and start the node.

On Windows the database is located in `%LOCALAPPDATA%\\concordium\database-v3`.

**If you don't care about losing logs and baker keys** then you can achieve the same by stopping the node and running `concordium-node-reset-data`

**Comment by ismailsrbst** [comment]
Thank you very much!
