### ISSUE TITLE
bug in wallet - cant transfer tokens

### ISSUE THREAD

**Issue by Yurbason** [Concordium/Testnet4-Challenges#517]
bug in wallet
there is no way to move tokens that were in the stake, even after 170+ hours after the removal of the baker

```
./concordium-client account show Yurbason                     
Local name:            Yurbason
Address:               3K8S8xSV71yd75Rxzjm3LCdRoLD29jmogKLrfphjqf2GPbwwqF
Balance:               9670.342366 GTU
Nonce:                 8760
Encryption public key: 993fdc40bb8af4cb75caf8a53928d247be6285784b29578a06df312c28854c1bfac2fd0183967338b578772398d41201b5a4d9253fc7f8ce8e971b94ca8240064f26b7539ac2e96f0b7c8341c514fde75094bdac9eec6708f0f7a241e1aef4cc

Baker: none
```

![photo_2021-02-23_14-06-06](https://user-images.githubusercontent.com/52459938/108835505-9fdb3700-75e0-11eb-9c35-f172084f36c7.jpg)

**Comment by Yurbason** [comment]
nodeid:05277e26b2cd4292
bakerid:84
accountaddress:3K8S8xSV71yd75Rxzjm3LCdRoLD29jmogKLrfphjqf2GPbwwqF
blockhash_addbaker:[489dc4f584c9dc76d19f08d0eb204d0c7f08d24025d4cc75c11e2f3c459a3719](https://dashboard.testnet.concordium.com/chain/489dc4f584c9dc76d19f08d0eb204d0c7f08d24025d4cc75c11e2f3c459a3719)
blockhash_removebaker:[72c47f0e05029b129b382195af516376228501fa61362389f20907c62dea9cb9](https://dashboard.testnet.concordium.com/chain/72c47f0e05029b129b382195af516376228501fa61362389f20907c62dea9cb9)

**Comment by concordium-cl** [comment]
Hi @Yurbason, it looks like you ran into a known issue on Android. Please have a look at #1 and let us know, in case your setup is different from the described. Thanks!

**Comment by Yurbason** [comment]
@concordium-cl 
Yes you are right
after reimporting wallets, everything worked as it should
unfortunately did not notice that they had already published a similar problem before :)
