### ISSUE TITLE
retrieve_minified_logs-linux-v1 tool collects all logs BUT with ‘Runtime:0’

### ISSUE THREAD

**Issue by eBusinessMan** [Concordium/Testnet4-Challenges#666]
hi, Team.  
I have completed 720h running task. 
**BUT** I met an issue when retrieving log with _retrieve_minified_logs-linux-v1 tool_. 
My steps are as below:

> 1.  stop the node :      ./concordium-node-stop

> 2. retrieve logs:     ./retrieve_minified_logs-linux-v1

and a log file is prodused.

But When I open the log file, and find  'runtime:0',   shown as below:
![图片](https://user-images.githubusercontent.com/13031011/109841881-77a8a380-7c84-11eb-84a9-6c95ee9c4daf.png)

and this is my new log file :
[concordium-testnet-node-fc3425c17f4c8022158b47e4b36d1ecc8f678e43fa0d2c66bea67b8b50cb3c6d.log](https://github.com/Concordium/Testnet4-Challenges/files/6077747/concordium-testnet-node-fc3425c17f4c8022158b47e4b36d1ecc8f678e43fa0d2c66bea67b8b50cb3c6d.log)

Note:  I have retrieved and saved the old log file before node upgration on 06 Feb. And there is 'runtime:110' inside it.
But curious about the new log file retrieved currently.

Could team please help me check about the issue? 
By the way, Should I go ahead submit my (old&new) log files for Task-B1 now??

**Comment by eBusinessMan** [comment]
Besides,  and I found the last line inside new log file  is always '2021-03-03T01:50:44.520013378Z'. My node is still running again till now , and log seems stopping at '2021-03-03T01:50:44.520013378Z'.  Please help check. thanks

**Comment by concordium-cl** [comment]
@eBusinessMan, we are looking into it. It's good that you submitted and referred to this issue. We'll get back to you.

**Comment by concordium-cl** [comment]
@eBusinessMan: The [updated version](https://client-distribution-testnet.concordium.com/retrieve_minified_logs-linux-v2) of the tool is available now (but not published to logs.md yet). Please try it out!

**Comment by eBusinessMan** [comment]
hi, Team,  thanks for you great work for the issue.  I have retrieved the log files again and it shows 'Runtime' correctly. And I commit the new log files again just now : https://github.com/eBusinessMan/Testnet4-Challenges/commit/19fd44ea1ae67ed9d8f01be0d421f9f303eb5e21

!!!!!please note!!!!!: I have completed >=720h on 3 Mar before Deadline.  Please DON'T Mistake disqualifying my Submit. Thanks
