### ISSUE TITLE
Bug iOS 14.3

### ISSUE THREAD

**Issue by bagi-avt** [Concordium/Testnet4-Challenges#69]
Page "Accounts" click row "Shielded Balance". Button disappears "three lines". 
To make it appear, you need to click "More" details then "Accounts"

**Comment by eb-concordium** [comment]
Hi bagi-avt,

Thanks for letting us know. Can you provide a screenshot demonstrating what what you experienced?

Kind regards,
Emil, Concordium Support

**Comment by bagi-avt** [comment]
Отправлено с iPhone

**Comment by jens-concordium** [comment]
Hi Bagi-avt,

I just managed to recreate your scenario. The "burger-menu" is actually not meant to appear in the shielded balance page at all, so something is not working as intended indeed.

Good catch, and thanks for letting us know.

**Comment by concordium-cl** [comment]
Created internal ticket to remove burger menu from shielded balance; issue here will be closed.
