### ISSUE TITLE
Bug or Error ?

### ISSUE THREAD

**Issue by okannako** [Concordium/Testnet4-Challenges#86]
`concordium-client transaction send-gtu-scheduled --schedule "50 at 2021-01-01T12:00:00Z" --receiver B --sender A`

I used this code for a task, and at that moment it didn't cause any problems, and I could see the fee and amount that it cut in both the client and the wallet. But after about 7 hours, this use did not appear in my wallet, it was deleted.  It could be a wallet-related error or bug. I think it should be checked. Thank you

**Comment by eb-concordium** [comment]
Hi okannako,

Thanks for letting us know. We will investigate this. 

Kind regards,
Emil, Concordium Support

**Comment by okannako** [comment]
> Hi okannako,
> 
> Did you use that exact command with the date 2021-01-01? If so, the transaction will get rejected, and the fee will still be charged.
> 
> Or did you use another date?
> 
> Kind regards,
> Emil, Concordium Support

: No, I wrote it about 4 hours later.  I also checked the Client that the process was dated forward

**Comment by eb-concordium** [comment]
Hi okannako,

Thanks for letting us know. Can you please provide the hash of the transaction and your account address?

**Comment by okannako** [comment]
> Hi okannako,
> 
> Thanks for letting us know. Can you please provide the hash of the transaction and your account address?

I have not saved the hash of the transaction. sender address: 4r9SDJoy3mn2DxDLwiyL6Bvpr4jdR2oDHtXCsLcP1SnoW8ZqxX
Thank you.

**Comment by abizjak** [comment]
I can see that this account has made 12 transfers with schedule (at this time).

If they do not appear in the mobile wallet that is indeed a bug. Can you clarify where exactly you are checking these values?

**Comment by okannako** [comment]
> I can see that this account has made 12 transfers with schedule (at this time).
> 
> If they do not appear in the mobile wallet that is indeed a bug. Can you clarify where exactly you are checking these values?

İşlemi yaptığım anda hem client de hem de cüzdan da görünmüştü ancak daha sonra yukarıda yazdığım gibi oldu ve cüzdan da geçmişe dönük baktığımda görünmüyordu.
Kullandığım kod: `./concordium-client transaction send-gtu-scheduled --schedule "60 at 2021-01-29T10:00:00Z" --receiver 3RupT7HtrPazZ6ibmGYKCu8568Aphs2vYtUhaQYLApjhJxudCN --sender 4r9SDJoy3mn2DxDLwiyL6Bvpr4jdR2oDHtXCsLcP1SnoW8ZqxX`

**Comment by okannako** [comment]
As soon as I made the transaction, both the client and the wallet appeared, but then it happened as I wrote above, and the wallet also did not appear in retrospect.
The code I use: `./concordium-client transaction send-gtu-scheduled --schedule "60 at 2021-01-29T10:00:00Z" --receiver 3RupT7HtrPazZ6ibmGYKCu8568Aphs2vYtUhaQYLApjhJxudCN --sender 4r9SDJoy3mn2DxDLwiyL6Bvpr4jdR2oDHtXCsLcP1SnoW8ZqxX`

**Comment by abizjak** [comment]
My question was where exactly does the value not appear. I can see that the transactions happened.

The Concordium ID app can display the transaction in different places and the display will vary over time.
- the transaction in the transaction list, i.e., when you click on the account
- the release schedule for the account (click on the upper right of the screen)
- the balance of the account (both general balance and at disposal)

When you send the transaction and before the scheduled release time (in your example 2021-01-29T10:00:00Z) the transaction on the receiving account should appear in both places, and the balance should be visible as part of general balance, but not at disposal.

After the scheduled release time the transaction should be visible under the list of transactions on the account, but the release schedule will disappear, and the GTU will become part of the "at disposal" balance.

**Comment by okannako** [comment]
> My question was where exactly does the value not appear. I can see that the transactions happened.
> 
> The Concordium ID app can display the transaction in different places and the display will vary over time.
> 
> * the transaction in the transaction list, i.e., when you click on the account
> * the release schedule for the account (click on the upper right of the screen)
> * the balance of the account (both general balance and at disposal)
> 
> When you send the transaction and before the scheduled release time (in your example 2021-01-29T10:00:00Z) the transaction on the receiving account should appear in both places, and the balance should be visible as part of general balance, but not at disposal.
> 
> After the scheduled release time the transaction should be visible under the list of transactions on the account, but the release schedule will disappear, and the GTU will become part of the "at disposal" balance.

I saw such an error and wanted to report it. The Concordium app also appeared at the time of the transaction and then disappeared. Thank you

**Comment by concordium-cl** [comment]
Hi @okannako, note that the releases in the release schedule (the burger icon in the upper right corner) disappear when their time comes and their amount is released to the "at disposal" amount of the account. So the list empties itself by time and shows no entries anymore when all locked up amounts are released. Could that have confused you?

The transaction in the transfer list of the account should not disappear. This applies to both sender and receiver account. And of course the released amounts should not disappear from the balance of the receiver.

Could you please verify that on your setup again? It might be best to try to reproduce that with a fresh command with future releases. And pls save the transaction hash for us. Because if indeed your amounts do not add to the general balance after being released, that's a bad bug and we would be very interested in that. Thanks for your help in advance!

**Comment by concordium-cl** [comment]
No user response; issue closed.
