### ISSUE TITLE
connection error 

### ISSUE THREAD

**Issue by DursunONER** [Concordium/Testnet4-Challenges#96]
I noticed that my node is not trading today. I encountered errors when I connected to my virtual machine and checked it. I saw that I have no name on the dashboard. And I thought it was caused by this error: Cannot establish connection to GRPC endpoint. I tried running the node again but again I encountered the error

**Comment by DursunONER** [comment]
my node name was 'Dursun ONER'.

**Comment by DursunONER** [comment]
> I noticed that my node is not trading today. I encountered errors when I connected to my virtual machine and checked it. I saw that I have no name on the dashboard. And I thought it was caused by this error: Cannot establish connection to GRPC endpoint. I tried running the node again but again I encountered the error

**Comment by DursunONER** [comment]
> I noticed that my node is not trading today. I encountered errors when I connected to my virtual machine and checked it. I saw that I have no name on the dashboard. And I thought it was caused by this error: Cannot establish connection to GRPC endpoint. I tried running the node again but again I encountered the error
my node name was 'Dursun ONER'.
I tried to stop and start the node again. But This error appears

CallStack (from HasCallStack):
  error, called at src/Concordium/GlobalState/Persistent/BlobStore.hs:158:27 in globalstate-0.1.0.0-4mfcLNBPEaUFg1z2xbTa0n:Concordium.GlobalState.Persistent.BlobStore
��SV: warning: too many hs_exit()s
2021-02-02 21:22:47,317 INFO exited: p2p-client (exit status 0; expected)
^C2021-02-02 21:22:48,319 INFO spawned: 'p2p-client' with pid 2460
2021-02-02 21:22:48,320 WARN received SIGINT indicating exit request
2021-02-02 21:22:48,321 INFO waiting for collector, p2p-client to die
2021-02-02T21:22:48.347186480Z: INFO: Starting up p2p_client version 0.4.8!
2021-02-02T21:22:48.347770240Z: INFO: Application data directory: "/var/lib/concordium/data"
2021-02-02T21:22:48.347955600Z: INFO: Application config directory: "/var/lib/concordium/config"
2021-02-02T21:22:48.348109630Z: INFO: Network: enabled
2021-02-02T21:22:48.348269880Z: INFO: Log level: info
2021-02-02T21:22:48.348577960Z: INFO: My Node ID is 147be8d37bdd80de
2021-02-02T21:22:48.353635379Z: INFO: Starting consensus layer
2021-02-02T21:22:48.354026329Z: INFO: Starting up the consensus thread
2021-02-02T21:22:48.354828149Z: INFO: Starting up the consensus layer
p2p_client-cli: too few bytes
From:   demandInput

![11](https://user-images.githubusercontent.com/71280079/106665091-f2639d80-65b6-11eb-9d24-2acbd030394b.png)

**Comment by DursunONER** [comment]
> > I noticed that my node is not trading today. I encountered errors when I connected to my virtual machine and checked it. I saw that I have no name on the dashboard. And I thought it was caused by this error: Cannot establish connection to GRPC endpoint. I tried running the node again but again I encountered the error
> > my node name was 'Dursun ONER'.
> > I tried to stop and start the node again. But This error appears

> ![11](https://user-images.githubusercontent.com/71280079/106665091-f2639d80-65b6-11eb-9d24-2acbd030394b.png)

**Comment by DursunONER** [comment]
When I stop the node and try to start it again I get this error
![11](https://user-images.githubusercontent.com/71280079/106668094-e8dc3480-65ba-11eb-9d71-5e4399ab354c.png)

**Comment by abizjak** [comment]
Unfortunately this indicates a database error.

The only solution for this is to stop the node, remove the database, and start the node again, letting it catch up.

There are two ways to delete the database.
- (if on linux or mac) remove the `~/.local/share/concordium/database-v3` directory
- use the `concordium-reset-data`. **Note that this will also delete any logs you have of the previous run, so if you are participating in the baker challenges you should not do this.**

**Comment by DursunONER** [comment]
If I delete the ~ / .local / share / condition / database-v3 directory, won't my logs be lost? and after I delete this directory, what should I do is rebuild?

**Comment by abizjak** [comment]
No, your logs will not be lost if you just delete that directory. However if you need the logs I would be extra cautious and do the following.

1. run `concordium-node-retrieve-logs` to get your current logs, and store them somewhere for backup
2. run `concordium-node-stop` to stop the current node if it is running
3. delete the `~/.local/share/concordium/database-v3` directory
4. run `concordium-node`

Does that make sense?

**Comment by DursunONER** [comment]
my node is synchronizing. after sync, do I have to do the tasks again?

**Comment by concordium-cl** [comment]
@DursunONER, what tasks? 
The above instructions? Well, hopefully not. 
The challenge tasks? Which challenges were you executing? Can you achieve a complete submission with the data you have? Can you check all the boxes?

**Comment by DursunONER** [comment]
I did what you said. i was doing b4,T1,T2,T3,T4 tasks . there are T1.log, enc.log, T3.log and T4.log tasks in $HOME/Documents/concordium-software file

**Comment by DursunONER** [comment]
What should I do after syncing? Will I upload the Backup I made? If Yes, How Do I Install?

**Comment by DursunONER** [comment]
What should I do after syncing? Will I restore the backup? If Yes, How Do I Install?

**Comment by concordium-cl** [comment]
@DursunONER: You don't need to install the backup log. When your node caught up to the chain, you can retrieve logs again and check the uptime in the new log. If everything worked smoothly, you should have the total uptime there from start and not just the hours since restart.
